# -*- coding: utf-8 -*-
'''
Highly divisible triangular number - Problem 12
Issue - #13

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''
from math import ceil

def checkflag(num):
    flag = True
    count = 2
    for c in range(2, int(ceil(num / 2)) + 2):
        if num % c == 0: count += 1
    flag = False if(count > 500) else True
    print(num, flag)
    return flag

flag = True

tnum = 0
icount = 1

while flag:
    tnum += icount
    #print(tnum, icount)
    flag = checkflag(tnum)
    icount += 1
print(tnum)
