# -*- coding: utf-8 -*-
'''
Problem  - Distinct powers
Issue - #32
Description -
How many distinct terms are in the
sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
'''

m = set()
n = 101
for x in range(2, n):
    for y in range(2, n):
        m.add(x ** y)
print(len(m))